FROM python:3.7.3
ADD . / node/
ENV PORT 25010
CMD (export PYTHONPATH=/node; cd ./node/; pip install -r ./requirements.txt; python3 -u ./submarine/ConnectionModule/src/NodeRouting.py -p ${PORT} -i 0.0.0.0)
