# Globals for Persistence

DATABASE_HOSTNAME = "127.0.0.1"
DATABASE_PORT = "27017"
DATABASE_NAME = "submarine"
MESSAGE_COLLECTION = "messages"

MESSAGE_PERSISTENCE_ERROR_MESSAGE = "Couldn't persist the message"

MESSAGE_RESEND_INTERVAL_IN_MINUTES = 5
MESSAGE_SAVED_TIME_IN_DAYS = 1